FPS = 60


# Window size
WINDOW_WIDTH  = 1200
WINDOW_LENGTH = 800

# Grid size
GRID_WINDOW_WIDTH  = int(WINDOW_WIDTH*3/5)
GRID_WINDOW_LENGTH = int(WINDOW_LENGTH*9/10)

HALF_GRID_WINDOW_WIDTH  = int(GRID_WINDOW_WIDTH//2)
HALF_GRID_WINDOW_LENGTH = int(GRID_WINDOW_LENGTH//2)

# Cam bound
CAM_BOUND_X = int(GRID_WINDOW_WIDTH)
CAM_BOUND_Y = int(0)

CAM_BOUND_WIDTH  = int(WINDOW_WIDTH - GRID_WINDOW_WIDTH)
CAM_BOUND_LENGTH = int(CAM_BOUND_WIDTH*576/1024) 



# Object info box
OBJ_INFO_WIDTH = int(WINDOW_WIDTH - GRID_WINDOW_WIDTH)
OBJ_INFO_LENGTH = int(WINDOW_LENGTH - GRID_WINDOW_LENGTH)
OBJ_INFO_POS_X = int(GRID_WINDOW_WIDTH)
OBJ_INFO_POS_Y = int(CAM_BOUND_LENGTH)

#scaled rate
SCALED_RATE_X = 5
SCALED_RATE_Y = 5

SPLITED_SCALE_RATE = 0.75
SPLITED_SCALE_RATE_X = SCALED_RATE_X*SPLITED_SCALE_RATE

#my car path and size
MY_CAR_IMAGE_PATH = "./Tool/img/my_car.png" # 수정 필요
MY_CAR_SIZE = (2*SCALED_RATE_X, 4*SCALED_RATE_Y)

#my car front center
MY_CAR_FRONT_CENTER_COORDINATE_X = GRID_WINDOW_WIDTH/2
MY_CAR_FRONT_CENTER_COORDINATE_Y = GRID_WINDOW_LENGTH/2 - MY_CAR_SIZE[1]/2

#size between grids X and Y
GRID_X_SIZE =  8*SCALED_RATE_X
GRID_Y_SIZE = 10*SCALED_RATE_Y

#font size and font type
FONT_SIZE = 10


#draw scan info position
TEXT_POS_X = 50
TEXT_POS_Y = 30


#colors
BLUE =          (0,   0,   255)
RED =           (255, 0,   0)
GREEN =         (0,   255, 0)
WHITE =         (255, 255, 255)
GRAY =          (128, 128, 128)
BLACK =         (0,   0,   0)
YELLOW =        (255, 204, 0)
BRIGHT_GRAY =   (226, 226, 226)
DARK_GRAY =     (98,  98,  98)
PINK =          (0xFF,0xC0,0xCB)
INDIGO =        (0x4B,0x00,0x82)
AQUAMARINE =    (0x7F,0xFF,0xD4)
SKYBLUE =       (0x87,0xCE,0xEB)
#fps(Frames Per Second)
FPS = 10

MODE_ON = 1
MODE_OFF = 0

