# FPS = 60


# # Window size
# WINDOW_WIDTH  = 1200
# WINDOW_LENGTH = 800

# # Grid size
# GRID_WINDOW_WIDTH  = int(WINDOW_WIDTH*3/5)
# GRID_WINDOW_LENGTH = int(WINDOW_LENGTH*9/10)

# HALF_GRID_WINDOW_WIDTH  = int(GRID_WINDOW_WIDTH//2)
# HALF_GRID_WINDOW_LENGTH = int(GRID_WINDOW_LENGTH//2)

# # Cam bound
# CAM_BOUND_X = int(GRID_WINDOW_WIDTH)
# CAM_BOUND_Y = int(0)

# CAM_BOUND_WIDTH  = int(WINDOW_WIDTH - GRID_WINDOW_WIDTH)
# CAM_BOUND_LENGTH = int(CAM_BOUND_WIDTH*576/1024) 



# # Object info box
# OBJ_INFO_WIDTH = int(WINDOW_WIDTH - GRID_WINDOW_WIDTH)
# OBJ_INFO_LENGTH = int(WINDOW_LENGTH - GRID_WINDOW_LENGTH)
# OBJ_INFO_POS_X = int(GRID_WINDOW_WIDTH)
# OBJ_INFO_POS_Y = int(CAM_BOUND_LENGTH)

# #scaled rate
# SCALED_RATE_X = 5
# SCALED_RATE_Y = 5

# SPLITED_SCALE_RATE = 0.75
# SPLITED_SCALE_RATE_X = SCALED_RATE_X*SPLITED_SCALE_RATE


# #size between grids X and Y
# GRID_X_SIZE =  8*SCALED_RATE_X
# GRID_Y_SIZE = 10*SCALED_RATE_Y

# #font size and font type
# FONT_SIZE = 10


# #draw scan info position
# TEXT_POS_X = 50
# TEXT_POS_Y = 30



# #fps(Frames Per Second)
# FPS = 15

# MODE_ON = 1
# MODE_OFF = 0

